Add OpenAPI Specification v3.1 objects
Neoteroi/essentials-openapi pull request #41
Opened 2024-01-27 21:24 UTC by tyzhnenko

2024-01-30 16:58 UTC, RobertoPrevato commented
Hi @tyzhnenko 
Thank You for your contribution! It seems there is more analysis needed because I see several properties that were removed from OpenAPI specification in v3 are still included in the classes you proposed in this PR.

By the way - the complexity of OAD makes me feel that supporting it fully in web frameworks is a work for people like Hermes from Futurama! 😁

2024-01-30 16:59 UTC, RobertoPrevato requested changes

2024-01-30 16:59 UTC, RobertoPrevato commented on openapidocs/v31.py
> +class Schema(OpenAPIElement):
It seems we should add `content_encoding` and `content_media_type` explicitly to the Schema object.

2024-01-30 17:00 UTC, tyzhnenko commented
@RobertoPrevato I'll take a look at your comments and make changes. Thanks to the review

2024-01-30 23:09 UTC, tyzhnenko commented on openapidocs/v31.py
> +    nullable: Optional[bool] = None
@RobertoPrevato it seems the type can be a string or a list with types. A lot of examples contain only one type in the `type` field, and a validator accepts those formats.

2024-01-30 23:41 UTC, tyzhnenko commented on openapidocs/v31.py
> +    type: Union[None, str, ValueType] = None
@RobertoPrevato it seems the type can be a string or a list with types. A lot of examples contain only one type in the type field, and a validator accepts those formats. ([ref.](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.1)]

2025-04-27 09:18 UTC, RobertoPrevato commented
Thank You @tyzhnenko! I am merging this. In the next days I will try to incorporate this into BlackSheep, and I am considering to keep a single implementation for `v3` for simplicity and due to lack of time to maintain several implementations within a major version of the OpenAPI specification.

2025-04-27 09:19 UTC, merged